# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'postmethod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ObjectMapper', '~> 3.5'

  # Pods for postmethod

end
